attacks:
  - name: bitflip
    parameters:
      bits_to_flip: 50
      population_size: 80
      epochs: 300
      mutation_chance: 0.05
      mutation_max: 20
      percent_of_population_to_keep: 0.3

  - name: "grid_occlusion"
    parameters:
      rho_grids: 8
      line_width: 1
  - name: "grid_occlusion"
    parameters:
      rho_grids: 16
      line_width: 1
  - name: "fim"
    parameters:
      epsilon: 16
      steps: 10
      alpha: 1.6
      pretrained: "vggface2"
      face_only: true

  - name: "fim"
    parameters:
      epsilon: 16
      steps: 10
      alpha: 1.6
      pretrained: "casia-webface"
      face_only: true
